version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - ../.env
    networks:
      - prisma-network
